# Generated by Django 4.1.3 on 2022-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='codpostal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='numar_tel',
            field=models.IntegerField(),
        ),
    ]
