# Generated by Django 4.1.3 on 2022-11-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0002_alter_post_codpostal_alter_post_numar_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
