# Generated by Django 4.1.3 on 2022-11-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0004_remove_post_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
