# Generated by Django 4.1.3 on 2022-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0005_addbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nume_prenume_parinte', models.CharField(max_length=100)),
                ('Adresa', models.CharField(max_length=100)),
                ('cod_postal', models.IntegerField()),
                ('numar_tel', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('cnp_ul_parintelui', models.IntegerField()),
                ('Nume_prenume_copil', models.CharField(max_length=100)),
                ('initiala_tatalui', models.CharField(max_length=100)),
                ('cnp_copil', models.IntegerField()),
            ],
        ),
    ]
