# Generated by Django 4.1.3 on 2022-11-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0006_inscriere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscriere',
            old_name='Nume_prenume_copil',
            new_name='Nume_Prenume_copil',
        ),
    ]
