# Generated by Django 4.1.3 on 2022-11-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0007_rename_nume_prenume_copil_inscriere_nume_prenume_copil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriere',
            name='Nume_Prenume_copil',
        ),
        migrations.RemoveField(
            model_name='inscriere',
            name='cnp_copil',
        ),
        migrations.RemoveField(
            model_name='inscriere',
            name='cnp_ul_parintelui',
        ),
        migrations.RemoveField(
            model_name='inscriere',
            name='initiala_tatalui',
        ),
    ]
