# Generated by Django 4.1.3 on 2022-11-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradi', '0008_remove_inscriere_nume_prenume_copil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscrieri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeparinte', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('codpostal', models.IntegerField()),
                ('nrtel', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('cnpparinte', models.IntegerField()),
                ('numecopil', models.CharField(max_length=100)),
                ('initiala', models.CharField(max_length=100)),
                ('cnpcopil', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Inscriere',
        ),
    ]
